##### XÂY DỰNG CHƯƠNG TRÌNH KIỂM ĐỊNH Z (HOẶC T) CHO CÁC BÀI TẬP SAU

Gợi ý:

- Số liệu được sinh ngẫu nhiên theo phân phối chuẩn
- Sử dụng gói phần mềm statsmodels để tiến hành kiểm định
- Đối với các bài tập kiểm định giả thuyết thì sinh viên cần phát biểu các giả thuyết (bằng tiếng Việt) $H_{0}$ và $H_{a}$ trước khi lập trình kiểm định

In [13]:
from statsmodels.stats.weightstats import ztest
import numpy as np
import random
from scipy import stats as st
from statsmodels.stats.weightstats import ttest_ind

Bài 1: You’re a Q/C inspector for Gallo. The sample standard deviation for 2-liter bottles is .05 liters.  A random sample of 100 bottles showed sasmple mean = 1.99 liters.  What is the 90%  confidence interval estimate of the true mean amount in 2-liter bottles? 

In [6]:
def bai_1():
    sample_mean = float(input('Sample mean = ')) #  trung bình mẫu
    sigma = float(input('Sigma =')) # độ lệch chuẩn
    n = int(input('Mẫu =')) # mẫu 
    khoang_tin_cay = float(input('khoảng tin cậy  = ')) 
   
    print('Lượng nước trung bình chai trong khoảng:', st.norm.interval(khoang_tin_cay , loc=sample_mean, scale=sigma))
    # z test
    null_mean = float(input('null_mean = ')) # 2 l
    #sinh mẫu ngẫu nhiên
    samples = np.random.normal(sample_mean,sigma,n)
    ztest_Score, p_value= ztest(samples, value = null_mean, alternative='larger')
    print('z = ', ztest_Score,
           'p = ', p_value)
    if(p_value <  (1-khoang_tin_cay)/2):
      print("Có bằng chứng để bác bỏ giả thuyết H0")
    else:
      print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
    
bai_1()

Sample mean = 1.99
Sigma =0.5
Mẫu =100
khoảng tin cậy  = 0.9
Lượng nước trung bình chai trong khoảng: (1.1675731865242636, 2.812426813475736)
null_mean = 2
z =  0.3254110006089204 p =  0.3724350154568069
Chưa có bằng chứng để bác bỏ giả thuyết H0
None


Bài 2: You’re a time study analyst in manufacturing.  You’ve recorded the following task times (min.): 3.6, 4.2, 4.0, 3.5, 3.8, 3.1. What is the 90% confidence interval estimate of the population mean task time? 

In [9]:
def nhap_mau2():
    list1 = []
    n = int(input('nhập mẫu n ='))
    for i in range(n):
        x = float(input('nhập giá trị :'))
        list1.append(x)
    return list1
list1 = nhap_mau2()
print(list1)


nhập mẫu n =3
nhập giá trị :12
nhập giá trị :3
nhập giá trị :2
[12.0, 3.0, 2.0]


In [11]:
class Bai_2():
    def __init__(self,list1):
        self.l1 = list1
    def gia_tri_tb(self):
        sum1 = 0
        for i in self.l1:
            sum1+= i
        return sum1/len(self.l1)
    def kq(self):
        khoang_tin_cay = float(input('nhap khoảng tin cậy :'))
        sigma = np.std(self.l1)  
        kq = st.norm.interval(khoang_tin_cay, loc=self.gia_tri_tb(), scale=sigma)

        print('thời gian trung bình thực hiện nhiệm vụ:', kq)
        ttest_Score, p_value = st.ttest_1samp(self.l1, 3.0)
        print('t = ',ttest_Score,', p = ',p_value)
        if(p_value <  (1-khoang_tin_cay)/2):
            print("Có bằng chứng để bác bỏ giả thuyết H0")
        else:
            print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
       
ADD = Bai_2(list1)
ADD.gia_tri_tb()
ADD.kq()


nhap khoảng tin cậy :0.9
thời gian trung bình thực hiện nhiệm vụ: (-1.7300962037108993, 13.06342953704423)
t =  0.8386278693775346 , p =  0.4899386295493293
Chưa có bằng chứng để bác bỏ giả thuyết H0


 Bài 3: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes had $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

In [31]:
def bai_3():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    alpha = float(input('alpha ='))
    
    
    # t test
    ttest_Score, p_value = st.ttest_1samp(np.random.normal(sample_mean,sigma,n), null_mean)
    print("t =", ttest_Score,"p =",p_value)
    if(p_value <  alpha/2):
        print("Có bằng chứng để bác bỏ giả thuyết H0")
    else:
        print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
bai_3()

Mẫu n =25
Sample mean = 372.5
Sigma =25
Null_mean = 368
alpha =0.05
t : 0.5018706419719895 p : 0.620331715513063
Chưa có bằng chứng để bác bỏ giả thuyết H0
None


Bài 4: You’re a Q/C inspector.  You want to find out if a new machine is making electrical cords to customer specification: average breaking strength of 70 lb. with $\sigma$ = 3.5 lb.  You take a sample of 36 cords & compute a sample mean of 69.7 lb.  At the .05 level of significance, is there evidence that the machine is not meeting the average breaking strength?

In [7]:
def bai_4():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    alpha = float(input('alpha ='))
    
    # z test
    ztest_Score, p_value= ztest(np.random.normal(sample_mean,sigma,n), value = null_mean, alternative='larger')
    print('z = ', ztest_Score, '; p = ', p_value)
    if (p_value <  alpha):
        print("Có bằng chứng để bác bỏ giả thuyết H0")
    else:
        print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
bai_4()

Mẫu n =36
Ý nghĩa mẫu = 69.7
Sigma =3.5
Null_mean =70
alpha =0.0
z =  -0.4041850401561766 ; p =  0.6569616731440505
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 5: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ =  372.5.  The company has specified $\sigma$ to be 25 grams.  Test at the .05 level of significance.

In [16]:
def bai_5():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    alpha = float(input('alpha ='))
    
    # t test
    ttest_Score, p_value = st.ttest_1samp(np.random.normal(sample_mean,sigma,n), null_mean)
    print("t =", ttest_Score,"p =",p_value)
    if(p_value <  alpha/2):
        print("Có bằng chứng để bác bỏ giả thuyết H0")
    else:
        print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
bai_5()

Mẫu n =25
Ý nghĩa mẫu = 372.5
Sigma =25
Null_mean =368
alpha =0.05
t = 1.7366599198266515 p = 0.0952680993394877
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 6: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is at least 32 mpg. Similar models have a standard deviation of 3.8 mpg. You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg. At the .01 level of significance, is there evidence that the miles per gallon is less than 32?

In [17]:
def bai_6():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    alpha = float(input('alpha ='))
    
    # z test
    ztest_Score, p_value= ztest(np.random.normal(sample_mean,sigma,n), value = null_mean, alternative='larger')
    print('z = ', ztest_Score, '; p = ', p_value)
    if (p_value <  alpha):
        print("Có bằng chứng để bác bỏ giả thuyết H0")
    else:
        print("Chưa có bằng chứng để bác bỏ giả thuyết H0")
bai_6()

Mẫu n =60
Ý nghĩa mẫu = 30.7
Sigma =3.8
Null_mean =32
alpha =0.01
z =  -1.5934659832424416 ; p =  0.944472153201026
Chưa có bằng chứng để bác bỏ giả thuyết H0


Bài 7: Does an average box of cereal contain 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

In [18]:
def bai_7():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    
    # t test
    ttest_Score, p_value = st.ttest_1samp(np.random.normal(sample_mean,sigma,n), null_mean)
    print("p =",p_value)
  
bai_7()

Mẫu n =25
Ý nghĩa mẫu = 372.5
Sigma =15
Null_mean =368
t = 1.668519896196991 p = 0.10820843435314727


Bài 8: Does an average box of cereal contain more than 368 grams of cereal?  A random sample of 25 boxes showed $\overline{\rm x}$ = 372.5.  The company has specified $\sigma$ to be 15 grams.  Find the p-Value.

In [19]:
def bai_8():
    n = int(input('Mẫu n ='))
    sample_mean = float(input('Sample mean = '))
    sigma  = float(input('Sigma ='))
    null_mean = float(input('Null_mean = '))
    
    # t test
    ttest_Score, p_value = st.ttest_1samp(np.random.normal(sample_mean,sigma,n), null_mean)
    print("p =",p_value)
  
bai_8()

Mẫu n =25
Ý nghĩa mẫu = 372.5
Sigma =15
Null_mean =368
p = 0.0038790139463246794


Bài 9: You’re an analyst for Ford.  You want to find out if the average miles per gallon of Escorts is less than 32 mpg.   Similar models have a standard deviation of 3.8 mpg.  You take a sample of 60 Escorts & compute a sample mean of 30.7 mpg.  What is the value of the observed level of significance (p-Value)?

In [20]:
bai_9 = bai_8()
bai_9

Mẫu n =60
Ý nghĩa mẫu = 30.7
Sigma =3.8
Null_mean =32
p = 0.024204157607651853


Bài 10: Does an average box of cereal contain 368 grams of cereal?  A random sample of 36 boxes had a mean of 372.5 and a standard deviation of 12 grams. Test at the .05 level of significance.

In [ ]:
bai_10 = bai_6()
bai_10

Bài 11: You work for the FTC.  A manufacturer of detergent claims that the mean weight of detergent is 3.25 lb.  You take a random sample of 64 containers.  You calculate the sample average to be 3.238 lb. with a standard deviation of .117 lb.  At the .01 level of significance, is the manufacturer correct?

In [ ]:
bai_11 = bai_6()

Bài 12: Is the average capacity of batteries less than 140 ampere-hours?  A random sample of 20 batteries had a mean of 138.47 and a standard deviation of 2.66.  Assume a normal distribution. Test at the .05 level of significance.

In [ ]:
bai_12 = bai_5()

Bài 13: You’re a marketing analyst for Wal-Mart.  Wal-Mart had teddy bears on sale last week.  The weekly sales of bears sold in 10 stores was: 8  11  0   4   7   8   10   5   8   3. At the .05 level of significance, is there evidence that the average bear sales per store is more than 5?

In [ ]:
bai_13 = bai_5()